const FETCH_VIDEOS = 'FETCH_VIDEOS';
const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
const FETCH_VIDEOS_FAIL = 'FETCH_VIDEOS_FAIL';
const RESET_MESSAGE_AND_ERROR = 'RESET_MESSAGE_AND_ERROR';
const ADD_VIDEO = 'ADD_VIDEO';
const ADD_VIDEO_SUCCESS = 'ADD_VIDEO_SUCCESS';
const ADD_VIDEO_FAIL = 'ADD_VIDEO_FAIL';
const EDIT_VIDEO = 'EDIT_VIDEO';
const EDIT_VIDEO_SUCCESS = 'EDIT_VIDEO_SUCCESS';
const EDIT_VIDEO_FAIL = 'EDIT_VIDEO_FAIL';

export {
  FETCH_VIDEOS,
  FETCH_VIDEOS_SUCCESS,
  FETCH_VIDEOS_FAIL,
  RESET_MESSAGE_AND_ERROR,
  ADD_VIDEO,
  ADD_VIDEO_SUCCESS,
  ADD_VIDEO_FAIL,
  EDIT_VIDEO,
  EDIT_VIDEO_SUCCESS,
  EDIT_VIDEO_FAIL,
};
