const FETCH_VIDEOS = 'FETCH_VIDEOS';
const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
const FETCH_VIDEOS_FAIL = 'FETCH_VIDEOS_FAIL';
const RESET_MESSAGE_AND_ERROR = 'RESET_MESSAGE_AND_ERROR';

export {
  FETCH_VIDEOS,
  FETCH_VIDEOS_SUCCESS,
  FETCH_VIDEOS_FAIL,
  RESET_MESSAGE_AND_ERROR,
};
