const FETCH_VIDEOS = 'FETCH_VIDEOS';
const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
const FETCH_VIDEOS_FAIL = 'FETCH_VIDEOS_FAIL';

export { FETCH_VIDEOS, FETCH_VIDEOS_SUCCESS, FETCH_VIDEOS_FAIL };
